### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Get all exercises
GET http://localhost:7007/api/v1/exercise

### Create exercise
POST http://localhost:7007/api/v1/exercise
Content-Type: application/json

{
"name": "bicep curls",
  "muscleGroup": "lowerbody",
  "equipment": "weights and bench",
  "instructions": "make your hand touch your shoulder"
}

### Get exercise by id
GET http://localhost:7007/api/v1/exercise/1