### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create exercise
POST http://localhost:7007/api/v1/exercise
Content-Type: application/json

{
"name": "training",
  "muscleGroup": "chest",
  "equipment": "bar & bench",
  "instructions": "down and push",
  "externalId": "1"
}

### Get exercise by id
GET http://localhost:7007/api/v1/exercise/1